export const COUNT_CHANGE_ACTION_TYPE = '@@TRASH/COUNT_CHANGED';
export const SHOW_MODAL_ACTION_TYPE = '@@BOARDS/SHOW_MODAL';
export const SET_BOARD_NAME_ACTION_TYPE = '@@BOARDS/SET_NAME';
export const GET_BOARD_LIST_ACTION_TYPE = '@@BOARDS/GET_BOARD_LIST';
export const GET_LISTS_ACTION_TYPE = '@@BOARDS/GET_BOARD';
export const LOADING_ACTION_TYPE = '@@BOARDS/LOADING';

export const DRAG_CARD_ACTION_TYPE = '@@CARD/DRAG_CARD';
export const DROP_CARD_ACTION_TYPE = '@@CARD/DROP_CARD';
export const GET_LIST_ID_ACTION_TYPE = '@@LIST/GET_LIST_ID';

